kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: ${APP_NAME}
  labels:
    k8s-app: ${APP_NAME}
spec:
  replicas: ${REPLICAS}
  selector:
    matchLabels:
      k8s-app: ${APP_NAME}
  template:
    metadata:
      name: ${APP_NAME}
      labels:
        k8s-app: ${APP_NAME}
    spec:
      containers:
      - name: ${APP_NAME}
        image: ${IMAGE_URL}
        resources:
          requests:
            cpu: ${REQUEST_CPU}
            memory: ${REQUEST_MEMORY}
          limits:
            cpu: ${LIMIT_CPU}
            memory: ${LIMIT_MEMORY}
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: File
        imagePullPolicy: Always
        securityContext:
          privileged: false
      restartPolicy: Always
      imagePullSecrets:
        - name: ali-registry
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600