apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: APP_NAME
  name: APP_NAME
spec:
  replicas: REPLICAS_NUM
  selector:
    app: APP_NAME
    deploymentconfig: APP_NAME
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: APP_NAME
        deploymentconfig: APP_NAME
    spec:
      containers:
      - name: APP_NAME
        image: IMAGE_URL
        imagePullPolicy: Always
        ports:
        - containerPort: 8778
          protocol: TCP
          name: jolokia
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        resources:
          limits:
            cpu: LIMIT_CPU
            memory: LIMIT_MEMORY
          requests:
            cpu: REQUEST_CPU
            memory: REQUEST_MEMORY
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: "tmp-volume-1"
        - mountPath: /var/local/krb5conf
          name: krb5config
        - mountPath: /var/local/hbase-site
          name: hbase-site-file
        - mountPath: /var/local/keytab
          name: keytab
        - mountPath: /var/local/gateway-ca
          name: gateway-ca
        - mountPath: /var/local/mib-pfx
          name: mib-pfx
        - mountPath: /var/local/mib-jks
          name: mib-jks
      dnsPolicy: ClusterFirst
      nodeSelector:
        region: primary
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: "tmp-volume-1"
      - configMap:
          name: hbase-site-file
        name: hbase-site-file
      - configMap:
          name: krb5config
        name: krb5config
      - name: keytab
        secret:
          secretName: keytab
      - name: gateway-ca
        secret:
          secretName: gateway-ca
      - name: mib-pfx
        secret:
          secretName: mib-pfx
      - name: mib-jks
        secret:
          secretName: mib-jks
  test: false
  triggers:
  - type: ConfigChange
